Repository innocentDE/osu-flex, pull requests merged in 2024-01, with the labels that each got.

#34 Added /help command for a listing of all aviable bot commands and added a class with constants
  src/main/java/com/flex/Main.java
  src/main/java/com/flex/data/FlexData.java
  src/main/java/com/flex/discord/Bot.java
  src/main/java/com/flex/discord/commands/HelpCommand.java
  src/main/java/com/flex/discord/embeds/HelpEmbed.java
  src/main/java/com/flex/discord/embeds/JoinEmbed.java
  src/main/java/com/flex/discord/embeds/ScoreEmbed.java
  src/main/java/com/flex/discord/entities/ScoreEmbedData.java
  src/main/java/com/flex/discord/listeners/GuildListener.java
Labels: refactoring, feature

#54 Score index
  src/main/java/com/flex/discord/embeds/ScoreEmbed.java
  src/main/java/com/flex/discord/entities/ScoreEmbedData.java
  src/main/java/com/flex/osu/Flex.java
  src/main/java/com/flex/osu/api/requests/FlexRequests.java
  src/main/java/com/flex/osu/entities/OsuData.java
Labels: feature

#56 Added algorithm for picking dominant color of the avatar
  src/main/java/com/flex/discord/entities/ScoreEmbedData.java
  src/main/java/com/flex/osu/api/requests/utility/ColorFinder.java
Labels: feature, ux
